name: Forge Tests

on:
  push:
    branches: [main]

jobs:
  e2e_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Foundry
        uses: onbjerg/foundry-toolchain@v1
        with:
          version: nightly

      - name: Install submodules
        run: forge install

      - name: Run Forge tests
        env:
          ETH_RPC_URL: ${{secrets.ETH_RPC_URL}}
        run: make e2e profile=production

  integration_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Foundry
        uses: onbjerg/foundry-toolchain@v1
        with:
          version: nightly

      - name: Install submodules
        run: forge install

      - name: Run Forge tests
        env:
          ETH_RPC_URL: ${{secrets.ETH_RPC_URL}}
        run: make integration profile=production

  deep_fuzz_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Foundry
        uses: onbjerg/foundry-toolchain@v1
        with:
          version: nightly

      - name: Install submodules
        run: forge install

      - name: Run Forge tests
        env:
          ETH_RPC_URL: ${{secrets.ETH_RPC_URL}}
        run: ./test.sh -p super_deep -t testDeepFuzz_

  shallow_fuzz_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Foundry
        uses: onbjerg/foundry-toolchain@v1
        with:
          version: nightly

      - name: Install submodules
        run: forge install

      - name: Run Forge tests
        env:
          ETH_RPC_URL: ${{secrets.ETH_RPC_URL}}
        run: ./test.sh -p deep -t testShallowFuzz_

  invariant_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Foundry
        uses: onbjerg/foundry-toolchain@v1
        with:
          version: nightly

      - name: Install submodules
        run: forge install

      - name: Run Forge tests
        env:
          ETH_RPC_URL: ${{secrets.ETH_RPC_URL}}
        run: make invariant profile=super_deep

  local_simulations:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Foundry
        uses: onbjerg/foundry-toolchain@v1
        with:
          version: nightly

      - name: Install submodules
        run: forge install

      - name: Run Forge tests
        env:
          ETH_RPC_URL: ${{secrets.ETH_RPC_URL}}
        run: make local-sim

  mainnet_simulations:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Foundry
        uses: onbjerg/foundry-toolchain@v1
        with:
          version: nightly

      - name: Install submodules
        run: forge install

      - name: Run Forge tests
        env:
          ETH_RPC_URL: ${{secrets.ETH_RPC_URL}}
        run: make mainnet-sim
